### ISSUE TITLE
Drawing of pedestal is very slow, especially when showing hotspots

### ISSUE THREAD

**Issue by jan-hudec** [FGMEMBERS/Douglas-Dc3#3]
When starting up at night (I love night flights navigating by motorways), showing hotspots is absolutely essential for selecting fuel tank and being able to position mixture lever properly. However displaying the hotspots on pedestal causes _extremely_ slow redrawing. Like many seconds per frame.

**Comment by helijah** [comment]
Selon Jan Hudec notifications@github.com:

> When starting up at night (I love night flights navigating by motorways),
> showing hotspots is absolutely essential for selecting fuel tank and being
> able to position mixture lever properly. However displaying the hotspots on
> pedestal causes _extremely_ slow redrawing. Like many seconds per frame.

Hi Jan

As I have already said to Israel, requests or suggestions for models of my shed
MUST obligatorily be sent to me!

Regarding the CD 3, it has been improved by people who do not know work. No
optimization has been made. He will soon receive a very big update. Obviously
anything that will not have been sent to me will be lost.

I am a designer of model that continues to maintain its models. Only with more
than 300 models, I can't do all in 2 jours.Cela takes time.

Regards Emmanuel

**Comment by jan-hudec** [comment]
@helijah, where do you prefer patches to be sent then?

**Comment by FGDATA** [comment]
@jan-hudec 

there is no problem for you to modify any of the FGMEMBERS repositories. Regardless of what @helijah  seems interested in make you believe; you have no obligatory terms.

Nothing is going to be lost, even after Helijah send us his updates.

Also, if you want to send a patch to helijah, his email address is found in the README of most of his aircraft.

**Comment by jan-hudec** [comment]
@FGDATA, yes. And I created this issue which he clearly did get notification about it. If I knew his workflow, I like to be kind and do whatever fits it. But since I didn't notice an obvious instruction for reporting issues on his hangar web nor in his answer here, I don't know.

**Comment by FGDATA** [comment]
He wants an email with the changes. Basically.
He wants 100% decision of whether what you work on goes anywhere or not. 

Again, his email is in the README file.

**Comment by helijah** [comment]
Selon Jan Hudec notifications@github.com:

> @helijah, where do you prefer patches to be sent then?

Mu email addres is present in all Readme.txt files in all models of my hangar :

embaranger@free.Fr

Regards Emmanuel

**Comment by helijah** [comment]
Selon Jan Hudec notifications@github.com:

> @helijah, where do you prefer patches to be sent then?

My email addres is present in all Readme.txt files in all models of my hangar :

embaranger@free.Fr

Regards Emmanuel

**Comment by FGDATA** [comment]
@jan-hudec 

Keep in mind that you are totally authorized to push commits to the FGMEMBERS repositories. Those [b]are not[/b] Helijah's repositories, but separate forks. 

You can email him, and send him notifications of changes you propose for him. And also, can push changes here. There is not such "obligatory" terms to send and email or to subdue to helijah.
