### ISSUE TITLE
no model was loaded except a pilot

### ISSUE THREAD

**Issue by tonghuix** [FGMEMBERS/Douglas-Dc3#4]
it only load a pilot modal, all modal of the plane and cockpit, everything was gone.

**Comment by ghost** [comment]
I don't know much about this one here, but for me, this version works http://pattenflightgear.wifeo.com/douglas-dc3-c47.php maybe you can try it out?

**Comment by tonghuix** [comment]
It seems my problem, it built in Ubuntu 16.04 and fail to load DC-3. However, I re-built FG on Debian Stretch, it succeed.

**Comment by ghost** [comment]
Okay, great

**Comment by FGDATA** [comment]
> `It seems my problem, it built in Ubuntu 16.04 and fail to load DC-3. However, I re-built FG on Debian Stretch, it succeed.

Good to hear. In my computer it works beautifully. 
It has several improvements over patten's link

IAHM-COL`
